CREATE TABLE articles (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users not null,
 user_email text,
 title text,
 contents text,
 categories text,
 inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table articles enable row level security;

create policy "Individuals can create articles." on articles for
   insert with check (auth.uid() = user_id);

create policy "Public articles are viewable by the owner."
  on articles for select using ( auth.uid() = user_id );

create policy "Individuals can update their own articles." on articles for
   update using (auth.uid() = user_id);

create policy "Individuals can delete their own articles." on articles for
   delete using (auth.uid() = user_id);

create policy "Articles are public." on articles for
   select using (true);