
CREATE TABLE comments (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users not null,
 user_email text,
 article_id bigint references articles (id) not null,
 contents text,
 inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table comments enable row level security;

create policy "Individuals can create comments." on comments for
   insert with check (auth.uid() = user_id);

create policy "Public comments are viewable by the owner."
  on comments for select using ( auth.uid() = user_id );

create policy "Individuals can update their own comments." on comments for
   update using (auth.uid() = user_id);

create policy "Individuals can delete their own comments." on comments for
   delete using (auth.uid() = user_id);

create policy "Comments are public." on comments for
   select using (true);