import { useRouter } from "next/router";
import { useEffect, useState,useContext } from "react";
import { supabase } from "../utils/supabase";
import ArticleCard from "../components/ArticleCard";
import Button from "../components/Button";
import UserContext from '../components/UserContext';
import Head from 'next/head'

export default function Dashboard() {
    const [articles, setArticles] = useState([]);
    const [fetchError, setFetchError] = useState(null);
    const [loading, setLoading] = useState(true);
    const { user } = useContext(UserContext);
    const router = useRouter();




    useEffect(() => {
        fetchArticles();
      }, []);
    
      const fetchArticles = async () => {
        try {
          setLoading(true);
          const { data, error } = await supabase
            .from("articles")
            .select("*")
            .eq("user_id", user?.id);
    
          if (error) throw error;
          setArticles(data);
        } catch (error) {
          alert(error.message);
        } finally {
          setLoading(false);
        }
      };
    
      if (loading) {
        return <div>Fetching articles...</div>;
      }
      const handleDelete = async (id) => {
        try {
          const { data, error } = await supabase
            .from("articles")
            .delete()
            .eq("id", id)
            .eq("user_id", user?.id);
          fetchArticles();
          if (error) throw error;
          alert("Article deleted successfully");
        } catch (error) {
          alert(error.message);
        }
      };
    
      return (
        <div>
          <Head>
            <title>Nextjs x Supabase</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <div>
            {!user ? (
              <div>
                <p>
                  Welcome to Adrenargy. Kindly Login to your account or sign in for
                  a demo
                </p>
              </div>
            ) : (
              <div>
                <p>
                  Hello <span>{user.email}</span>,
                  Welcome to your dashboard
                </p>
                {articles?.length === 0 ? (
                  <div>
                    <p>You have no articles yet</p>
                    <Button className="bg-gray-200 dark:bg-gray-600"
                        onClick={() => router.push("/create")}>Create article
                    </Button>
                  </div>
                ) : (
                  <div>
                    <p>Here are your articles</p>
                    <ArticleCard data={articles} handleDelete={handleDelete} />
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      );
    }