import { useRouter } from "next/router";
import { useEffect, useState, useContext } from "react";
import { supabase } from "../utils/supabase";
import ArticleCard from "../components/ArticleCard";
import Button from "../components/Button";
import UserContext from '../components/UserContext';
import Head from 'next/head'

export default function Dashboard() {
    const [articles, setArticles] = useState([]);
    const [loading, setLoading] = useState(true);
    const { user } = useContext(UserContext);
    const router = useRouter();
    useEffect(() => {
        fetchArticles();
    }, []);
    const fetchArticles = async () => {
        try {
            setLoading(true);
            const { data, error } = await supabase
                .from("articles")
                .select("*")
                .eq("user_id", user?.id);

            if (error) throw error;
            setArticles(data);
        } catch (error) {
            alert(error.message);
        } finally {
            setLoading(false);
        }
    };
    if (loading) {
        return <div>Fetching articles...</div>;
    }
    const handleDelete = async (id) => {
        try {
            const { data, error } = await supabase
                .from("articles")
                .delete()
                .eq("id", id)
                .eq("user_id", user?.id);
            fetchArticles();
            if (error) throw error;
            alert("Article deleted successfully");
        } catch (error) {
            alert(error.message);
        }
    };
    return (
        <div className="flex justify-center items-center">
            <Head>
                <title>Nextjs x Supabase</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col justify-center items-center">
                {!user ? (
                    <div>
                        <p>
                            Welcome to our Blog. You are not logged in.
                        </p>
                    </div>
                ) : (
                    <div>
                        <p className="text-center mt-4">
                            Hello <span className="font-bold">{user.email}</span>,
                            Welcome to your dashboard
                        </p>
                        {articles?.length === 0 ? (
                            <div className="flex flex-col justify-center items-center mt-4">
                                <p>You have no articles yet</p>
                                <Button className="bg-gray-200 dark:bg-gray-600"
                                    onClick={() => router.push("/create")}>Create article
                                </Button>
                            </div>
                        ) : (
                            <div className="justify-center items-center">
                                <p className="text-center mt-4">Here are your articles</p>
                                <ArticleCard data={articles} handleDelete={handleDelete} />
                                <div className="flex flex-col items-center">
                                    <Button className="bg-gray-200 dark:bg-gray-600 "
                                        onClick={() => router.push("/create")}
                                    >Create article
                                    </Button>
                                </div>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}